### ISSUE TITLE
mp.dj() return undefined

### ISSUE THREAD

**Issue by maxqui26** [goto-bus-stop/miniplug#35]
mp.dj() return `undefined` if the actual dj is bot.
it's normal things, a bug or i'm just bad ???

**Comment by goto-bus-stop** [comment]
Thanks for the report! This should be fixed in v1.6.2.

**Comment by Burkes** [comment]
@goto-bus-stop What you did seem to have made `mp.user(botID)` return the bot user object, but `mp.user()` still doesn't work.

**Comment by goto-bus-stop** [comment]
It's not supposed to 😛 There's already `mp.dj()` for the current DJ and `mp.me()` for the bot user. I don't think `mp.user()` without an argument should do anything else

**Comment by Burkes** [comment]
Ahh, I see the issue now, my bad then.
